name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extension:
          - logout
          - theme-toggler
          - topbar-text

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install JupyterLab
        run: python -m pip install -U "jupyterlab>=4.0.0,<5"

      - name: Lint the extension
        run: |
          set -eux
          jlpm
          jlpm run lint:check

      - name: Build the extension
        working-directory: packages/${{ matrix.extension }}-extension
        run: |
          set -eux
          python -m pip install .

          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupyterlab-${{ matrix.extension }}-extension.*OK"

          python -m jupyterlab.browser_check
